//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniShoppingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mallar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mallar()
        {
            this.Photos = new HashSet<Photo>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_info { get; set; }
        public string product_price { get; set; }
        public string product_count { get; set; }
        public Nullable<int> product_brand_id { get; set; }
        public Nullable<int> product_category_id { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photos { get; set; }
    }
}
