//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniShoppingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageWant
    {
        public int wantmessage_id { get; set; }
        public Nullable<int> wantmessage_user_id { get; set; }
        public string wantmessage_text { get; set; }
    }
}
