//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniShoppingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int order_id { get; set; }
        public Nullable<int> order_status_id { get; set; }
        public Nullable<int> order_user_id { get; set; }
        public string order_product { get; set; }
        public string order_adress { get; set; }
        public string order_count { get; set; }
        public Nullable<System.DateTime> order_time { get; set; }
    
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual User User { get; set; }
    }
}
