//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniShoppingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OthBxo
    {
        public int othbox_id { get; set; }
        public Nullable<int> otbox_user_id { get; set; }
        public Nullable<int> otbox_photo_id { get; set; }
    
        public virtual Photo Photo { get; set; }
        public virtual User User { get; set; }
    }
}
